- ECIPs/ECIP-1054.md
Enable the outstanding Ethereum Foundation _Spurious Dragon_ and _Byzantium_ network protocol upgrades on the Ethereum Classic network in a hard-fork code-named _Atlantis_ to enable maximum compatibility across these networks.
To sync with https://github.com/etclabscore/ECIPs/pull/10
> ECIP-1054: Atlantis Hardfork Meta

- ECIPs/ECIP-1054.md
> Update Atlantis Testing Schedule

- ECIPs/ECIP-1057.md
https://github.com/ethereumclassic/ECIPs/issues/65
> ECIP-1057: Cold Staking

- ECIPs/ECIP-1054.md
> ECIP-1054: Atlantis was accepted with target 8_772_000

- ECIPs/ECIP-1056.md
Enable the outstanding Ethereum Foundation _Constaninople_ and _Petersburg_ network protocol upgrades on the Ethereum Classic network in a hard-fork code-named _Agharta_ to enable maximum compatibility across these networks.
ref https://github.com/etclabscore/ECIPs/pull/13
> ECIP-1056: Agharta Hardfork Meta

- ECIPs/ECIP-1000.mediawiki
• corrected some spelling
• adjusted grammar
• added step numbers to workflows
• added formatting for clarity
• corrected some links
• added some subtitles for clarity
> General adjustments and further adaptations to the ECIP-1000 text

- ECIPs/ECIP-1000.mediawiki
This adds the proposed initial list of ECIP editors. Please feel free to propose yourself or recommend others by commenting on this PR or make a pull request to branch `sp-ecip-editors`.
> Add initial list of ECIP editors

- _config.yml
Added header_pages: 
networking.html 
and changed:
erc.html
to:
ecbp.html
> Added header_pages: networking.html and changed erc.html

- _specs/ecip-1044.md
> Changed category to ECBP

- networking.html
It was a file missing to complete ECIP types.
> Creating networking.html file

- _specs/ecip-1000.md
Some were on ethereumproject, updated to point to correct repo.
> fix: Change URLs to point to ethereumclassic repo

- _config.yml
- _specs/ecip-1013.md
- _specs/ecip-1021.md
- _specs/ecip-1044.md
- ecbp.html
- erc.html
- index.html
- networking.html
Changed file name from `erc.html` to `ecbp.html`
Changed title from `ERC` to `ECBP`.
Changed string `where:"category","ERC" %}` to `where:"category","ECBP" %}`
> Changed to ECBP

- _specs/ecip-1050.md
Changed type from 'ERC' to 'ECBP'.
> Changed type to ECBP

- _data/statuses.yaml
> Added Work-in-Progress status

- _specs/ecip-1050.md
> move ecip 1050 to last call

- _specs/ecip-1067.md
@sorpaas I dont know why this got changed. the link you put is to something else
> (re)corrected disscusion-to link

- ecip-X.md
Adjusted format of template ECIP to fit to the latest version of ECIP-1000.
> Adjusted format of template ECIP to fit ECIP-1000

- _specs/ecip-1015.md
On behalf of the author, adding his name as author and adding a license to the ECIP.
The authorship may be confirmed here from original document: https://github.com/ethereumproject/ECIPs/blob/master/ECIPs/ECIP-1015.md
The license selected for this ECIP is Apache 2.
> Adding author and license to ECIP-1015

- _specs/ecip-1043.md
> update 1043 discussion link

- SECURITY.md
- _specs/ecip-1076.md
Some minor wording updates I think need to be made.  You be the judge :)
> Wording changes Security.md & ecip-1076

- _specs/ecip-1061.md
> ecip-1061: move aztlan to last call

- _specs/ecip-1061.md
Update licensing to Apache 2.0, to reflect inclusion of specifications authored by Wei Tang under Apache 2.0 licensing.
> Update licensing to Apache 2.0 for ECIP-1061

- README.md
Rel #235 
:rabbit2: :tornado:  https://github.com/meowsbits/ECIPs/commit/7c3048010e8b609d30e634b9c2bb601f2a185970
> feat(README): add Discourse Archives list

- _specs/ecip-1082.md
Original document here: https://github.com/ethereumclassic/ECIPs/blob/master/_specs/ecip-1082.md
Revised document rendered: https://github.com/ethereumclassic/ECIPs/blob/ad181baeb6361873d5e77bd3eaa945d63b1ad904/_specs/ecip-1082.md
> ECIP-1082: Last Call

- _specs/ecip-1088.md
Closes #314
Closes #298
Closes #262
Closes #227
> ECIP-1088: Accept Phoenix

- Gemfile
- Gemfile.lock
Signed-off-by: meows <b5c6@protonmail.com>
https://github.com/github/personal-website/issues/166#issuecomment-570958419
> try pinning faraday dep to fix jekyll build

- _specs/ecip-randomX.md
> ECIP-1093: Change the ETC Proof of Work Algorithm to RandomX

- _specs/ECIP-0001.md
Withdrawing this ecip as it didn't have consensus. Integrated changes in ecip-1000 by means of PR https://github.com/ethereumclassic/ECIPs/pull/312
> Withdrawing ecip-0001

- _specs/ecip-1088.md
> Move ECIP-1088 "Phoenix" to Final.

- _specs/ecip-1080.md
cc @bobsummerwill 
I propose abandoning this because we decided for 1088 in the end. ref #334
> Withdraw ECIP-1080 "SELFBALANCE"

- _specs/ecip-1095.md
- _specs/ecip-vanilla-sha-3.md
> ECIP-1095:feat: add vanilla sha-3 ecip draft

- _specs/ecip-1095.md
as per #333
together with #354 
there will be a working group for SHA3 and Keccak256 formed asap, action items:
- working group to merge these proposals (Stevan & Alex)
- figure out and specify a proper transition from Ethash to the new algorithm
> Move ECIP-1095 "SHA-3" to Last Call

- _specs/ecip-proto-treasury-system.md
Draft. https://github.com/input-output-hk/ECIPs/blob/ecip-proto-treasury/_specs/ecip-proto-treasury-system.md
Discussion. https://github.com/ethereumclassic/ECIPs/issues/350 | https://github.com/input-output-hk/ECIPs/issues/2
> ECIP-1098 proto-Treasury system for ETC

- _specs/ecip-1096.md
- _specs/ecip-51-attack-protection-system.md
**Draft.** [51% Attack protection system based on Bitcoin Merged Mining](https://github.com/martinmedina/ECIPs/blob/patch-1/_specs/ecip-51-attack-protection-system.md) 
**Discussion.** https://github.com/ethereumclassic/ECIPs/issues/343
> ECIP 1096: 51% Attack protection system based on Bitcoin Merged Mining

- _specs/ecip-1043.md
> ECIP-1043: fix review year

- _specs/ecip-1095.md
closes #342 in favor or #13 
as per decision at call #362 (13)
> ECIP 1095: reject in favor of Keccak (1049)

- _specs/ecip-1100.md
For coordination with exchanges and mining pools, it's recommended to set the ECBP-1100 activation block to `11_380_000`.
> ECBP-1100: Propose Coordinated MESS Classic Activation

- _specs/ecip-1000.md
Removing myself from the editor list. Merge this when desired. The longer form version is at: https://dontpanicburns.medium.com/end-of-active-service-with-ethereum-classic-582edab2af7a
> rm: cody from Editors

- _specs/ecip-1099.md
which is active on mordor and mainnet now
closes #11 
closes #138 
closes #368
> 1099: move to final

- _specs/ecip-1000.md
> 1000: add faraggi as editor

- _specs/ecip-1103.md
ref #412 #424
block_now | time_to_fork | block_time | fork_block | fork_date
--- | --- | --- | --- | ---
3_916_709 | 1026180 | 15 | 3_985_893 | 2021-06-02
4_258_403 | 1648920 | 15 | 4_368_634 | 2021-06-09
12_784_531 | 5259720 | 13 | 13_189_133 | 2021-07-21
moving to last call as per #424 till june 4th
> ECIP 1103: propose timeline

- _specs/ecip-1103.md
Rel https://github.com/ethereumclassic/ECIPs/issues/412#issuecomment-851958585
> ECIP-1103: add client status

- _specs/ecip-1103.md
> move 1103 to final (mainnet)

- _specs/ecip-1104.md
I propose to _accept_ the current state of the ECIP
> Move ECIP-1104 to status Accepted

- _specs/ECIP-0001.md
- _specs/ecip-1000.md
please update permissions accordingly
> removing myself from ecip editors

- _specs/ecip-1000.md
Former Editors Alphabetize by Handle
Clean up an old PR from Stev. Alphabetize the Former Editor list like the Current Editor list sits.
> Former Editors Alphabetize

- _specs/ecip-1091.md
Fix Author format, Fix File path
> Fix Author format, Fix File path

- _specs/ecip-1087.md
> Fix Author format for website

- _specs/ecip-1081.md
- _specs/ecip-1090.md
> Fix 0001 ref on 1081 to 1090

- _specs/ecip-1049.md
+ Add WIP designation due to lack of ECIP-1000 compliance.
+ Add ECIP Editor Notes for sections not in compliance to ECIP-1000
+ Add reference link to CDC 22 Article.
> Update 1049 Title to appropriate status per ECIP-1000

- _specs/ecip-1107.md
Add WIP Disclaimer. Grammar. Formatting. Punctuation. Organize Sections to ECIP-1000. Clarify we is not the network, but a development team.
> 1107 - Add status Disclaimer

- _specs/ecip-1108.md
> Fix Link for Author

- _specs/ecip-1109.md
To be discussed on Tue 5th at 10AM EST/15:00 UTC at https://ethereumclassic.org/discord
This proposal targets ~Jan 31st 2024
> Set Spiral mainnet activation block

- _specs/ecip-1109.md
Move to Accepted status assuming the observation period is complete. Following the status path laid out in ECIP-1000.
Last Call (Observation) -> Accepted (Implementation) -> Final (Implemented)
> Update ecip-1109.md -> Accepted status

- _specs/ecip-1000.md
Update list to accurately reflect the perms in the repo.
> Update ECIP Editors to perms

- _specs/ecip-1111.md
- _specs/ecip-1112.md
- _specs/ecip-1113.md
- _specs/ecip-1114.md
This pull request proposes the inclusion of four Ethereum Classic Improvement Proposals (ECIPs) that collectively define the **Olympia Upgrade** — a coordinated protocol initiative introducing sustainable, decentralized funding and governance infrastructure for the Ethereum Classic network.
---
| ECIP # | Title | Type | Summary |
|--------|-------|------|---------|
| **[1111](https://ecips.ethereumclassic.org/ECIPs/ecip-1111)** | Olympia Network Upgrade | Meta | Activates EIP-1559 on Ethereum Classic and redirects `BASEFEE` to a protocol treasury. |
| **[1112](https://ecips.ethereumclassic.org/ECIPs/ecip-1112)** | Olympia Treasury Contract | Meta | Specifies an immutable treasury contract to receive and manage `BASEFEE` revenue at the protocol level. |
| …
> ECIP Submission: Olympia Upgrade — Protocol Funding and Governance Suite

- _specs/ecip-1109.md
- _specs/ecip-1111.md
- _specs/ecip-1112.md
- _specs/ecip-1113.md
- _specs/ecip-1114.md
> Olympia Second Draft: Community Review

- _specs/ecip-1111.md
- _specs/ecip-1112.md
- _specs/ecip-1113.md
- _specs/ecip-1114.md
+ Add Clarity, Consistency, Depth, Detail.
+ Adds more examples, specified in the Appendix sections: BASEFEE redirects, Treasury, Governance, Proposal Process.
+ Clearer writing regarding voting and upgradable voting systems to combat FUD/misinformation due to complex language and technical idea. Try to lift technical burden off the reader.
+ Reviewed for language and idea consistency throughout the four ECIPs since the exist now. Polishing earlier ECIPs (e.g., 1111) to reflect the existence of later drafted ECIPs (e.g., 1114)
+ Noted some specifically confusing text and replaced to clarify.
+ Improved tone and messaging throughout all four ECIPs, emphasizing the important messages of Olympia
+ Improved code examples and consistency throughout all ECIPs
+ Removed redundant statements
+ …
> Polishing ECIPs
