- ECIPs/ECIP-1060.md
I propose to upgrade the Kotti testnet to Cliquey (a.k.a. "Clique v2") to make it more robust and prevent it from getting stuck in future.
References https://github.com/ethereum/EIPs/pull/1955 https://github.com/goerli/eips-poa/issues/12
> ECIP-1060: Specify the Cliquey proof-of-authority engine.

- ECIPs/ECIP-1054.md
- ECIP-1054: Move to last call state.
- ECIP-1054: Explicitly override with `ATLANTIS_FORK_BLKNUM`
> ECIP-1054: Move to last call state.

- README.md
Corrected EIP to ECIP under `Active` status term.
> Correcting EIP -> ECIP typo

- _specs/ecip-1000.md
To adjust to the new ecips.ethereumclassic.org website:
I changed the old ECIP types which were "Standard Track", "Process" and "Informational" to the new ones which are:
• Standard Track
-- Core
-- Networking
-- Interface
-- ECBP (analogous to "ERC" in Ethereum)
• Meta
• Informational
I also added status terms `WIP` and `Active` to adjust them to our ECIP status reality, e.g. ECIP-1000 is `Active`.
> Adjusting ECIP types to the ECIP site format

- _specs/ecip-1043.md
Adding Discussion-to link to ECIP-1043 about fixing DAG: https://github.com/ethereumclassic/ECIPs/issues/138
> Adding Discussion-to link to ECIP-1043

- _specs/ecip-1054.md
Moves Atlantis to FINAL, closes #67 
Adds missing EIP-684, ref https://github.com/ethereum/EIPs/issues/2220 and https://github.com/ethereum/EIPs/pull/2252
> [ECIP-1054] Move Atlantis to Final, Add EIP-684

- _specs/ecip-1066.md
This creates an ECIP for the current active network description of Ethereum Classic mainnet. This will be the second ECIP document with the "active" status along with ECIP-1000.
> ECIP-1066: Active Ethereum Classic Network Description

- _specs/ecip-1056.md
> move ecip 1056 to last call

- _specs/ecip-1055.md
With author consent, transporting Flyclient ECLIP to ECIP in this repo.
Added "Flyclient" term in title as it is the common name for this kind of change.
> ECIP-1055: Flyclient - Succinct PoW Using Merkle Mountain Ranges

- _specs/invoke-signer.md
Im looking into defining a spec to specifically invoke a user’s preferred wallet app for signing (a tx or arbitrary data)
I think it's time for a standard that can accommodate the user to use a hardware wallet from a desktop browser dapp or open a separate wallet app from a mobile browser dapp etc...
Discussions to here please 👉: https://github.com/ethereumclassic/ECIPs/issues/147
> invoke-signer draft 0

- _specs/ecip-1016.md
With author consent, moving this ECIP to withdrawn as its contents are largely included and covered in ECIP-1000.
> Moving to Withdrawn Status

- _specs/ecip-1040.md
- _specs/ecip-1068.md
- _specs/ecip-1069.md
This adds the following specifications to ECIPs repo:
* ECIP-1040: The base layer of account versioning. The current rough consensus.
* ECIP-1068: Extension of ECIP-1040 to allow transaction to deploy multiple versions.
* ECIP-1069: Extension of ECIP-1040 to allow CREATE/CREATE2 to deploy multiple versions.
> ECIP-1040, ECIP-1068 and ECIP-1069: Account Versioning ECIPs and Extensions

- _specs/ecip-1000.md
This adds [MulanPSL](https://license.coscl.org.cn/MulanPSL/) into the "recommended license" section in ECIP-1000. From an initial look it fulfills most of the criteria we want for a specification license:
1. Explicit patent protection, similar to Apache-2.0.
2. Permissive.
3. It looks like some of the languages used in the license will make it work better in the Chinese jurisdiction, which some contributors might have preferences.
> ECIP-1000: Add MulanPSL into recommended licenses

- _specs/ecip-1061.md
ref https://github.com/ethereum/EIPs/pull/2332
> add eips to aztlan

- _specs/ecip-1072.md
- _specs/ecip-1073.md
- _specs/ecip-1074.md
This adds three new hard fork meta, with different options to apply the Istanbul upgrade in a backward compatible way:
* ECIP-1072: Apply Istanbul directly, but remove the offending EIP-1884.
* ECIP-1073: Apply Istanbul with account versioning ECIP-1040 / EIP-1702. Currently both Parity and Geth have the implementation required. However, the drawback, as discussed last time, is that this will require a new account version for every hard fork.
* ECIP-1074: Apply Istanbul with account versioning, and with forward-compatible EVM changes. Currently no client has implemented 39-UNGAS and 40-UNUSED yet, so this will require more work, and we will need to maintain our own ecosystem tools. However, it gives us a good future foundation for modifying EVMs further. This is basically combination of …
> ECIP-1072, ECIP-1073, ECIP-1074: Backward Compatible Options for Istanbul Hard Forks

- _specs/ecip-10746.md
- _specs/ecip-1076.md
This meta document is agnostic to any mining algorithm. Its sole purpose is specifying a process how to openly determine and select a mining algorithm for Ethereum Classic.
ref #174
> ECBP-1076: Mining algorithm change process

- _specs/ecip-1070.md
As per the Mining Call and Issue Link Summary: https://github.com/ethereumclassic/ECIPs/issues/174#issuecomment-557106181
Moving ECIP-1070: ProgPoW on ETC to Rejected Status with the agreement that someone who wants to champion this proposal can do so on a new ECIP in the future.
> Update ECIP-1070 Status to Rejected

- _specs/ecip-1072.md
This moves ECIP-1072 into last call status, with review period of 3 weeks, as discussed on the call.
> ECIP-1072: Fix name and move it to last call

- _specs/ecip-1072.md
- _specs/ecip-1073.md
- _specs/ecip-1074.md
Reverts #198 and move ECIP-1072 to withdrawn status.
Closes #207.
We already have ECIP-1061 that specifies the hardfork. Stop messing around with Ethereum Classic.
> ECIP-1072: Move to withdrawn status

- _specs/ecip-1056.md
as agreed on the call today:
- add `review-period-end: 2019-12-19` meta data
- update block number to `9_573_000` on Ethereum Classic Mainnet (January 15, 2020)
closes #175 
note: agharta will be moved to accepted after the review period ends without any subsequent call unless the spec will be openly disputed.
> ecip-1056: add review period and block to agharta

- _specs/ecip-1000.md
While this license looks like it could be a great choice, it has not undergone legal due diligence like the other options.
Bob is chasing OSI to ensure that there is legal consensus that this license is in compliance with the Open Source Definition.
See https://opensource.org/docs/osd and see https://opensource.org/approval.
If MulanPSL gets that approval then I would have no objection.
Adding it was premature.
> Remove MulanPSL as a Recommended License.

- _specs/ecip-1000.md
- _specs/ecip-do_not_dox.md
Both soc1c and meowbits have made crystal clear that they do not want their real names in ECIP-1000.
> Remove doxing of ECIP Editors.

- _specs/ecip-1048.md
It was implemented a long time ago, but the ECIP was never updated.
We have to move it to Final Call first and then after is has been in that status, we can move it to Accepted, and then on to Final.
This is just house-keeping.
> Progress ECIP-1048 (Clique) to Final Call.

- _specs/ecip-1081.md
- _specs/ecip-do_not_dox.md
Seems this ECIP was merged without a number. The actual underlying correction proposed was done in ECIP-1000 through another PR https://github.com/ethereumclassic/ECIPs/pull/267, so this ECIP may either get a number and moved to "Active" so it agrees with the ECIP process format, or it may be deleted.
> ECIP-1081: No number in this ECIP

- _specs/ecip-1079.md
Feature-enable specifications conventionally use block numbers as inclusive
starting points, as opposed to last-without variables.
This commit edits the specification section assuming that that was what was
intended.
Rel #281
> ECIP-1079: feature timing convention block number

- _specs/ecip-1078.md
Feature-enable specifications conventionally use block numbers as inclusive
starting points, as opposed to last-without variables.
This commit edits the specification section assuming that that was what was
intended.
> ECIP-1078: feature timing convention block number

- _specs/ecip-1051.md
There has been no work on this proposal (or the earlier IOHK treasury proposal).
There is broad consensus that changing the block rewards to add treasury model is unacceptable.
The Monetary Policy (ECIP-1017) defines the ETC system and gives multi-decade certainty to all ETC ecosystem participants.
If we need to have a discussion of this on ETC Core Developers call then we should.
And then Reject it.
> ECIP-1051: Reject "Ethereum Classic Treasury system"

- _specs/ecip-1057.md
Other than Dexaran himself, there is no support for this proposal with the ETC ecosystem.
Proposals of this kind (like PoolTogether on ETH - https://www.pooltogether.com/) can happen just fine with no need for consensus across the ecosystem.
I propose we Reject this proposal.   It could be passed as Informational, I suppose, but there is really no need for there to be an ECIP for this application level proposal.
Even at application level, you would not need/want an ECIP for this until there were multiple implementations and this was become an architectural best practice.
Best, I think, to reject.    A new ECBP could be written which generalized the pattern and that might be accepted.
> ECIP-1057: Reject "Cold Staking"

- _specs/ecip-1052.md
This requires the Treasury.
Both the Treasury and this Auditing proposal on top run counter to ECIP-1017 monetary policy.
Auditing is a good idea, but should not be centralized into the block rewards.
This runs counter to ETC philosophy and principles and should be rejected.
Perhaps this is raised in an ETC Core Developers call, and formally rejected?
> ECIP-1052: Reject "Smart-contract Security Auditing core"

- _specs/ecip-1063.md
This is just a bad idea, and is never going to happen.
Sorry, Jesse.
But we should reject this and clear out cognitive load.
> ECIP-1063: Reject "Integrated decentralized oracles and smart contracts"

- _specs/ecip-1061.md
- _specs/ecip-1078.md
- _specs/ecip-1079.md
Move ECIP-1078 ("fix") to Last Call.
Move ECIP-1079 ("redo") to Withdrawn.
Aztlán has activated on the Mordor testnet, so can no longer be withdrawn.
Proceeding with "fix" appears to be our best option.
> Move ECIP-1078 ("fix") to Last Call.  Move ECIP-1079 ("redo") to Withdrawn.

- _specs/ecip-1084.md
- _specs/ecip-hard-cap-gaslimit-in-protocol.md
Hard cap on the gaslimit for the ETC mainnet as an in-protocol consensus rule.
From the block that this ECIP was activated, gaslimit would follow a
curve defined in this proposal rather than being subject to miner voting.
> ECIP-1084: Hard cap on the gaslimit for the ETC mainnet as an in-protocol consensus rule.

- _specs/ecip-1082.md
- _specs/ecip-_.md
EIP-2124 (`forkid`) and EIP-2364 (`eth/64`) propose discovery protocol modifications which depend on lists of fork values. In case these changes are adopted and implemented on Ethereum Classic networks, this ECIP defines canonical lists of forks numbers for inclusion in the generation and validation steps of these "ForkID" schemes.
- https://eips.ethereum.org/EIPS/eip-2124
- https://eips.ethereum.org/EIPS/eip-2364
This specification describes a set of forks which exclude TheDAO fork event block(s) from `forkid` calculations, as well as excluding all forthcoming `blockNumber % 5000000 == 0` blocks that, according to the algorithmdescribed in ECIP-1017 and enabled on ETC Mainnet and some testnets, will see reduced block reward values.
> ECIP-1082: Fork identifier (`forkid`) fork list specification

- _specs/ecip-1080.md
This should have happened at the same time as ECIP 1078: Phoenix EVM and Protocol Upgrades ("Aztlán fix") was moved.
Also correcting "type" and "category" from Meta to Standards Track.
That was a cut-and-paste error.
> Move ECIP 1080: SELFBALANCE opcode to Last Draft.

- _specs/ecip-1048.md
Kotti has been live for over a year.
Clique is implemented in Parity-Ethereum, Multi-Geth and Hyperledger Besu.
This ECIP just got left unprocessed.
> Move ECIP-1048 Clique proof-of-authority consensus protocol to Final.

- _specs/ecip-1050.md
It has been in Last Call since October.
People are using this standard in the real world.
The standard is not changing.
This is a best practice, not consensus.
> Move ECIP 1050: Status Codes to Final.

- _specs/ecip-1086.md
Issues with the _Aztlán_ protocol upgrades were identified and sufficiently patched with the _Phoenix_ protocol upgrades. However, the subsequent activation of these upgrades on the _Kotti_ and _Mordor_ testnets revealed inconsistencies between client implementations. This document proposes a patch for the aforementioned testnets.
The [EIP-2200](https://eips.ethereum.org/EIPS/eip-2200) defines structured definitions of net-gas metering for the `SSTORE` opcode. This EIP was activated in a bundle called [EIP-1679](https://eips.ethereum.org/EIPS/eip-1679) "Istanbul" on the Ethereum Foundation network and [ECIP-1061](https://ecips.ethereumclassic.org/ECIPs/ecip-1061) "Aztlán" on the Ethereum Classic network.
Notably, the difference here is that _Istanbul_ contained …
> ECIP-1086: SLOAD Gas Patch for the Testnets

- _specs/ecip-1081.md
It was replaced by ECIP-0001 ECIP process.
> Withdraw ECIP-1081 Do Not Dox ECIP Editors.

- _specs/ecip-1061.md
- _specs/ecip-1078.md
- _specs/ecip-1086.md
due to the multiple issues disclosed with aztlan and phoenix not being a sufficient fix and both testnets being broken, this pull request proposes to reject ecips-1061, 1078, 1086 due to security and stability concerns and to move on with writing a phoenix proposal from scratch. 
accepting this pull request requires community consensus in a publicly announced call.
> reject aztlan and pull phoenix

- _specs/ecip-1087.md
Don't touch Kotti; allow ECIP1061, ECIP1078, and ECIP1086 (EIP2200, EIP2200Disable) to continue as specified and implemented there.
Set Mordor ECIP1078 activation to 778507 (equivalent to ECIP1061), and rollback to 750000.
Kotti is a PoA network, so it doesn't simulate (ie test) ETC mainnet in the first place (at least not well) since it uses different consensus rules. If it is a public simulation and test of ETC mainnet, it isn't a good one. So we can follow the logic of A: Testnets-as-service.
Mordor is a PoW network, so is is a pretty good simulator of ETC mainnet. We can follow the logic of B: Testnets-as-test, and not only resolve the issue of EIP2200 correction, but improve the network's simulation of mainnet activation for ECIP1061 and ECIP1078.
---
Rendered: …
> ECIP1087 [Draft]: A way to resolve the ECIP1061/ECIP1078/ECIP1086/EIP2200 testnet fiasco (rollback Mordor, leave Kotti)

- _specs/ecip-1000.md
Moving Wei Tang (@sorpaas) from "current editors" to "former editors" to comply with their wish to disengage from Ethereum classic ecosystem. Reference: https://that.world/~classic/2020/06/10/deprecate/
> MV Sorpaas from current to former ecip editor

- _specs/ecip-1082.md
- _specs/ecip-1090.md
This version of the Ethereum Classic forkid specification corrects Kotti
forkid expectations, superseding [ECIP1082](https://ecips.ethereumclassic.org/ECIPs/ecip-1082). The change removes wrongly configured Ethash specifications
for the chain configuration, and in doing so removes two invalid forks (2000000, 5000000) from
the parameterized fork list.
Please see Pull Requests referenced below for implementation.
_EDIT_: This ECIP also documents itself as an "Active" ECBP, allowing further edits as necessitated by future network protocol upgrades.
> 1091: forkid v2 (kotti fix)

- _specs/ecip-1043.md
as per #333 
please note, that this also requires the following action items to be worked on in the next 3 weeks:
- instead of freezing the DAG, just freeze the size and rotate parameters (Cody, James?)
- research current DAG size, project future DAG size, find suitable block number
> Move ECIP-1043 DAG-Size Limit to Last Call

- _specs/ecip-1049.md
as per #333 
together with #355
there will be a working group for SHA3 and Keccak256 formed asap, action items:
- working group to merge these proposals (Stevan & Alex)
- figure out and specify a proper transition from Ethash to the new algorithm
also, specifically, ECIP-1049 needs a lot of text work, please follow the ECIP-X template file.
> Move ECIP-1049 "Keccak256" to Last Call

- _specs/51_attack_resistance.md
- _specs/ecip-1097.md
Draft. https://github.com/input-output-hk/ECIPs/blob/51-percent-attack-prevention/_specs/51_attack_resistance.md
Discussion. https://github.com/ethereumclassic/ECIPs/issues/348 | https://github.com/input-output-hk/ECIPs/issues/1
> ECIP-1097 Checkpointing for 51% Attack Resistance

- _specs/ecip-1099.md
Add ECIP 1099 "Calibrate Epoch Duration" draft.
> ECIP 1099: Calibrate Epoch Duration

- _specs/ecip-1043.md
closes #11
decision from call #362 (13)
superseded by: 1099 #368
> ECIP 1043: Move to Replaced by 1099

- _specs/ecip-1100.md
- _specs/ecip-11355.md
Drafting a "Best Practice" proposal for implementing a "Modified Exponential Subjective Scoring" algorithm for use in chain acceptance arbitration.
View the document [rendered](https://github.com/meowsbits/ECIPs/blob/ecbp/mess/_specs/ecip-1100.md).
Discussion to: https://github.com/ethereumclassic/ECIPs/issues/374
> ECBP-1100: Modified Exponential Subjective Scoring

- _specs/ecip-1093.md
It is apparent from the end of the [CDC #13](https://youtu.be/9r_q_z81eh4?t=3420) the `SHA3` ECIP-1049/1095 and accompanied mining algo change discussions are eating up too much bandwidth. The focus needs to remain on 51% attack solutions to stablize this network. So, I request to move ECIP-1093 to `Withdrawn` status to clear it from discussion.
`Withdrawn` - ECIP authors may decide to change the status between Draft, Deferred, or Withdrawn. The ECIP editor may also change the status to Deferred if no progress is being made on the ECIP. Source: https://github.com/ethereumclassic/ECIPs
Due to the observation that there is already a vocal opposition to changing the mining algorithm away from GPU-friendly Ethash. I believe any proposal suggesting a mining algo change would be contenious …
> Change Status of ecip-1093.md to Withdrawn

- _specs/ecip-1043.md
_specs/ecip-1043.md is NOT valid:	 {:status=>["is not included in the list"]}
frontmatterparser rescued from a nil death
Warning: _specs/ecip-1077.md 	 undefined method `keys' for nil:NilClass
Warning: _specs/ecip-1090.md 	 unknown attribute 'supersedes' for EcipValidator::Validator.
total:77, valid:74, invalid:1, errors:2
statuses: [["Withdrawn", 13], ["Active", 2], ["Final", 11], ["Draft", 35], ["Superseded", 3], ["Replaced", 1], ["Last Call", 1], ["Rejected", 9]]
> resolving build errors

- _specs/ecip-1000.md
I'm replacing myself with Stevan as ECIP Editor that is representing the ETC Cooperative.
> doc: Remove Yaz as ECIP Editor

- _specs/ecip-1100.md
- replaces _sin_ function with Vitalik's cubic antigravity function
- updates presented implementing code accordingly
- tries to better tackle the conceptual/principle part of it
- moves tentative mainnet "activation" block number to `11377500 (ETA Wednesay, 29 September 2020)` (again, not a hard fork, but configured in the same way)
- generally more and hopefully more useful implementation/specification details (eg for Besu devs)
:page_facing_up: View it [rendered](https://github.com/meowsbits/ECIPs/blob/ecbp/mess-2/_specs/ecip-1100.md).
> ECIP/ECBP-1100 MESS: adopt polynomial function, update code

- _specs/ecip-1099.md
Adds additional info to seedHash example, clarifying correct usage.
Motivated by: https://github.com/ethereumclassic/ECIPs/issues/397
> 1099: add additional comments to seedHash

- _specs/ecip-1049.md
+ move to Draft Status (Expired Last Call Review on Oct 9, 2020) due to material redraft of proposal.
+ Update Discussion Thread to new Redraft thread
+ Add Related Discussions Section for archived threads
> Admin Clean Up on ecip-1049.md

- _includes/eipnums.html
- networking.html
About #393 
Broken links was not only in the ECIP on issue but in all that had Superseded 
https://ecips.ethereumclassic.org/ECIPs/ecip-1099
https://ecips.ethereumclassic.org/ECIPs/ecip-1082
About #358
Networking should be category and not type
> Issues #393 and #358 solved

- _specs/ecip-1103.md
Per https://github.com/ethereumclassic/ECIPs/pull/425#issue-637825787, waiting period for _Last Call_ ends June 4th, today.
I am not aware of any last minute concerns or showstoppers raised.
> ecip-1103: bump status to accepted

- _specs/ecip-1084.md
There was no consensus around this change, which is nearly two years old now.
> Withdraw ECIP-1084 "Hard-cap gas-limit in protocol".

- _specs/ecip-1104.md
This PR proposes the following changes:
- Exclude EIP-3198: `BASEFEE` Opcode from Mystique 
- Add block number activation for each network based on the following calculations
* **Mordor** (1587460 seconds until Jan 10th 2022): `5_294_406 block + 1_587_460 secs / 13.3 secs/block ~= 5_414_000 block`
*  **Kotti** (2449694 seconds until Jan 20th 2022): `5_395_501 block + 2_449_694 secs / 15 secs/block ~= 5_559_000 block`
*  **Mainnet** (4264005 seconds until Feb 10th 2022): `14_181_120 block + 4_264_005 secs / 13.3 secs/block ~= 14_502_000 block`
- Change ECIP status to _Last call_
Ref: discussion #440
> [ECIP-1104] BASEFEE omit, activations, last call

- _specs/ecip-1049.md
Bob Summerwill is now currently championing ECIP-1049 and is an author of the proposal.
> Add Bob Summerwill as author for ECIP-1049

- _specs/ecip-1049.md
Per the bureaucratic regulations at [`ECIP Format and Structure`](https://github.com/ethereumclassic/ECIPs/blob/master/_specs/ecip-1000.md#ecip-format-and-structure).
> Editorial: Fix/ecip 1049

- _specs/ECIP-1107.md
This is a withdrawn ECIP that ECIP editors occasionally confuse with the active ECIP-1000 due to its numbering. Move to 1107 to correct this mistake given ECIP-1000's importance to the ECIP process. Save editors from having to redraft to the correct ECIP-1000 file.
recent example of this common editing error: https://github.com/ethereumclassic/ECIPs/pull/468
suggested fix: https://github.com/ethereumclassic/ECIPs/pull/468#pullrequestreview-893957293
> Adjust withdrawn ECIP-0001 to ECIP-1107 for editor/public clarity

- _specs/ecip-1049.md
There has not been any active work on this for several months.
There is not clear consensus on activation of the feature.
We have also missed the boat to make a transition prior to Ethereum's "The Merge" event, and the anticipated flood of hashrate into ETC.
> Withdraw ECIP-1049: "Change the ETC Proof of Work Algorithm to Keccak256"

- .github/workflows/jekyll.yml
Builds with docker's `jekyll/builder:latest` are failing because dependency hell.
See failing build at one of the latest PRs: https://github.com/ethereumclassic/ECIPs/runs/7325591137?check_suite_focus=true (https://github.com/ethereumclassic/ECIPs/pull/489)
Proof that this actually fixes it:
- https://github.com/meowsbits/ECIPs/tree/fix/jekyll
- https://github.com/meowsbits/ECIPs/actions/runs/2678686409
> peg docker jekyll/builder at v3 tag

- _specs/ecip-1105.md
This strips off all proposed context types and their
generic structure to instead propose only adding
a field 'ancestorHash' which defines a dependency
on some foregoing canonical block for a transaction.
> ecip-1105: becomes Ancestor Hash Appended proposal

- .github/workflows/ecip_validation.yml
Should fix the error here
https://github.com/ethereumclassic/ECIPs/actions/runs/4413046760/jobs/7733097142?pr=504
Reported here https://github.com/ethereumclassic/ECIPs/pull/504#issuecomment-1505696710
> .github/workflows: use upgraded ruby setup github action

- _specs/ecip-1000.md
Source: https://github.com/ethereumclassic/ECIPs/issues/505
- Move atoulme to Former editors list.
+ Add r0n1n's public ETC-centric organization.
@realcodywburns will you remove @atoulme from @ethereumclassic/ecip-editors access? Also while you're in there can you double check permissions in the repo and remove stale/inactive accounts that may have access due to involvement in the past? Much thanks!
> atoulme ECIP Editor resignation

- _specs/ecip-1047.md
2023 Update: This was accidentally observed on the network due to a large mining pool setting their default gas to this level. This prevented the development community from the ability to deploy Smart Contracts to Ethereum Classic briefly. Once observed, it was corrected and the mining pool set their gas limit to 8M. 
Additionally over three years, seems stale and dated.
ECIP-1000
"ECIPs should be changed from Draft or Last Call status, to Rejected, upon request by any person, if they have not made progress in three years. Such a ECIP may be changed to Draft status if the champion provides revisions that meaningfully address public criticism of the proposal, or to Last Call if it meets the criteria required as described in the previous paragraph." …
> Move ecip-1047.md to Deferred Status

- _specs/ecip-1100.md
- _specs/ecip-1110.md
Turn off the artificial finality mechanism [ECBP-1100's MESS (Modified Exponential Scoring)](https://ecips.ethereumclassic.org/ECIPs/ecip-1100) in [Core-Geth](https://github.com/etclabscore/core-geth) for Ethereum Classic.
Rendered document: https://github.com/meowsbits/ECIPs/blob/ecbp1110/_specs/ecip-1110.md
FYI I'll also be updating https://meowsbits.github.io/51-percent-docs/ this week, which provides some useful context.
> ECBP-1110: Deactivate MESS

- .github/workflows/jekyll.yml
Issue noticed here: https://github.com/ethereumclassic/ECIPs/pull/524
This CI issue: https://github.com/ethereumclassic/ECIPs/actions/runs/7514278707/job/20456978667?pr=524
According to this, might fix it: https://stackoverflow.com/questions/63435125/github-jekyll-workflow-failure
> .github/workflows: fix jekyll build issue
